version: "3.8"

services:
  # Serviço Apache com PHP
  apache:
    image: php:8.2-apache
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html # Diretório de código-fonte PHP
    depends_on:
      - mysql
    networks:
      - lamp_network
    ports:
      - "80:80" # Porta HTTP padrão
    restart: always

  # Serviço MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: adminroot # Senha do usuário root do MySQL
      MYSQL_DATABASE: pit2db # Nome do banco de dados a ser criado
      MYSQL_USER: admin # Nome do usuário do banco de dados
      MYSQL_PASSWORD: admin # Senha do usuário
    volumes:
      - mysql_data:/var/lib/mysql # Persistência de dados do MySQL
    networks:
      - lamp_network
    ports:
      - "3306:3306" # Porta do MySQL

  # Serviço Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mysql # Adminer depende do MySQL
    networks:
      - lamp_network
    ports:
      - "8080:8080" # Porta para acessar o Adminer via navegador
    restart: always

volumes:
  mysql_data: # Volume persistente para MySQL

networks:
  lamp_network:
    driver: bridge
