version: "3.8"

services:
  # Serviço MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # Senha do usuário root do MySQL
      MYSQL_DATABASE: pit2db # Nome do banco de dados a ser criado
      MYSQL_USER: root # Nome do usuário do banco de dados
      MYSQL_PASSWORD: root # Senha do usuário
    volumes:
      - mysql_data:/var/lib/mysql # Persistência de dados do MySQL
    networks:
      - lamp_network
    ports:
      - "3306:3306" # Porta do MySQL

  # Serviço Apache com PHP
  apache:
    image: php:7.4-apache
    container_name: apache
    volumes:
      - ./html:/var/www/html # Diretório de código-fonte PHP
    depends_on:
      - mysql
    networks:
      - lamp_network
    ports:
      - "80:80" # Porta HTTP padrão
    restart: always

  # Serviço PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql # Nome do serviço MySQL
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root # Senha do usuário root do MySQL
    ports:
      - "8080:80" # Porta para acessar o PHPMyAdmin via navegador
    networks:
      - lamp_network
    restart: always

volumes:
  mysql_data: # Volume persistente para MySQL

networks:
  lamp_network:
    driver: bridge
